import { Nunito } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Buzz",
  description: "Generated by create next app",
  icons: {
    icon: '/app/icon.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <link rel="icon" href="/app/favicon.ico" />
        </Head>
        <body className={font.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
